#!/usr/bin/python3
import sys
import os


def pra_fifo():
    pass


def pra_lru():
    pass


def pra_opt():
    pass


PRA_OPTIONS = {
    "fifo": pra_fifo,
    "lru": pra_lru,
    "opt": pra_opt
}

VALID_FRAME_RANGE = range(1, 257)

BACKING_STORE_FILEPATH = "BACKING_STORE.bin"


class TranslationLookasideBuffer:
    CAPACITY = 16
    
    def __init__(self):
        self.queue = []

    def enqueue(self, entry):
        if len(self.queue) >= self.CAPACITY:
            self.queue.pop(0)
        
        self.queue.append(entry)

    def lookup(self, page_number):
        for entry in self.queue:
            # Checks if in the queue, and valid bit set to 1
            # TODO: Once all bits confirmed, make sure valid bit is in correct location, or change the data structure to hold it
            if page_number in entry and entry[page_number][-1] == 1:
                # TLB hit
                return entry[page_number]
        # TLB miss
        return None


class PageTable:
    CAPACITY = 256

    def __init__(self):
        self.table = {}
        for i in range(self.CAPACITY):
            self.table[i] = (None, 0)
    
    def lookup(self, page_number):
        # Checks if in table, and valid bit set to 1
        # TODO: Once all bits confirmed, make sure valid bit is in correct location, or change the data structure to hold it
        if page_number in self.table and self.table[page_number][-1] == 1:
            # Page table hit
            return self.table[page_number]
        else:
            # Page table miss
            return None
    
    # This will alter the page table entry for targeted page
    # TODO: Confirm what info should contain
    def update(self, target_page, info: tuple):
        self.table[target_page] = info
        # TODO: May need to set bits here too as well


def handle_args() -> tuple[str, int, str]:
    """
    This function ensures the required arguments are provided,
    as well as sets defaults for any optional ones that weren't provided
    """
    args = sys.argv
    argc = len(args)
    frames, pra = None, None

    if argc < 2 or argc > 4:
        print("Usage: memSim <reference-sequence-file.txt> <FRAMES> <PRA>")
        exit()

    filepath = args[1]
    if not os.path.isfile(filepath):
        print(f"File '{filepath}' does not exist")
        exit()

    frames = int(args[2]) if argc >= 3 else 256
    pra = args[3].lower() if argc == 4 else "fifo"

    if frames not in VALID_FRAME_RANGE:
        print("<FRAMES> must be between 1-255")
        exit()

    if pra not in PRA_OPTIONS:
        print("<PRA> must be 'fifo', 'lru' or 'opt'")
        exit()

    return filepath, frames, pra


def read_backing():
    if not os.path.isfile(BACKING_STORE_FILEPATH):
        print("'{filepath}' does not exist")
        exit()
    
    backing_contents = []

    with open(BACKING_STORE_FILEPATH, 'rb') as file:
        row = file.read(256)
        backing_contents.append(row)

        while row:
            # extract row table (256 bytes)
            row = file.read(256)
            if not row:
                break
            backing_contents.append(row)

    return backing_contents


def main():
    filepath, frames, pra = handle_args()
    print(f"Running with {filepath=} {frames=} {pra=}") # Debug line: remove me later
    backing_store = read_backing()
    tlb = TranslationLookasideBuffer()
    page_table = PageTable()

    with open(filepath, "rb") as file:
        # TODO: Eventually do stuff with each virtual address
        for line in file:
            address = file.readline().strip()
            print(address)
    

if __name__ == "__main__":
    main()
