#!/usr/bin/python3
import sys
import os
import struct

# PRA will return frame to evict from physical memory
def pra_fifo() -> int:
    pass


def pra_lru() -> int:
    pass


def pra_opt() -> int:
    pass


PRA_OPTIONS = {
    "fifo": pra_fifo,
    "lru": pra_lru,
    "opt": pra_opt
}

VALID_FRAME_RANGE = range(1, 257)

BACKING_STORE_FILEPATH = "BACKING_STORE.bin"


class TranslationLookasideBuffer:
    CAPACITY = 16
    
    def __init__(self):
        self.queue = []

    def enqueue(self, page_number, frame, loaded):
        if len(self.queue) >= self.CAPACITY:
            self.queue.pop(0)
        
        self.queue.append({"page": page_number, "frame": frame, "loaded": loaded})

    def lookup(self, page_number):
        for entry in self.queue:
            # Checks if in the queue, and valid bit set
            if entry["page"] == page_number and entry["loaded"]:
                # TLB hit
                return entry["frame"]
        # TLB miss
        return None


class PageTable:
    CAPACITY = 256

    def __init__(self):
        self.table = []
        # Filling the table with default values
        for _ in range(self.CAPACITY):
            self.table.append({"frame": None, "loaded": False})

    def lookup(self, page_number):
        entry = self.table[page_number]
        # Page table hit
        if entry["loaded"]:
            return entry
        # Page table miss
        return None
    
    # This will alter the page table entry for targeted page
    def update(self, target_page, frame, loaded):
        self.table[target_page] = {"frame": frame, "loaded": loaded}
        # TODO: May need to set bits here too as well
    
    # If a page gets removed from a frame, need to update that entry (frame to None and loaded false)
    def unload(self, target_page):
        self.table[target_page] = {"frame": None, "loaded": False}


def handle_args() -> tuple[str, int, str]:
    """
    This function ensures the required arguments are provided,
    as well as sets defaults for any optional ones that weren't provided
    """
    args = sys.argv
    argc = len(args)
    frames, pra = None, None

    if argc < 2 or argc > 4:
        print("Usage: memSim <reference-sequence-file.txt> <FRAMES> <PRA>")
        exit()

    filepath = args[1]
    if not os.path.isfile(filepath):
        print(f"File '{filepath}' does not exist")
        exit()

    frames = int(args[2]) if argc >= 3 else 256
    pra = args[3].lower() if argc == 4 else "fifo"

    if frames not in VALID_FRAME_RANGE:
        print("<FRAMES> must be between 1-255")
        exit()

    if pra not in PRA_OPTIONS:
        print("<PRA> must be 'fifo', 'lru' or 'opt'")
        exit()

    return filepath, frames, pra


def split_virtual_address(addr: int) -> tuple[int, int]:
    # Shift high bits to right to get only the page bits with their appropriate significance
    page = addr >> 8
    # 0xFF has low 8 bits set to 1's and high set to 0's, so & with address to only get the low 8
    offset = addr & 0xFF

    return page, offset


def read_backing():
    if not os.path.isfile(BACKING_STORE_FILEPATH):
        print("'{filepath}' does not exist")
        exit()
    
    backing_contents = []

    with open(BACKING_STORE_FILEPATH, 'rb') as file:
        row = file.read(256)
        backing_contents.append(row)

        while row:
            # extract row table (256 bytes)
            row = file.read(256)
            if not row:
                break
            backing_contents.append(row)

    return backing_contents


def main():
    filepath, frames, pra = handle_args()
    print(f"Running with {filepath=} {frames=} {pra=}") # Debug line: remove me later
    backing_store = read_backing()
    tlb = TranslationLookasideBuffer()
    page_table = PageTable()
    physical_memory = [{"page": None, "content": None}] * frames
    page_list = []

    with open(filepath, "r") as file:
        for address in file:
            page, offset = split_virtual_address(int(address.strip()))
            print(f"{address=}, {page=}, {offset}") # Debug line: remove me later
            # Load in each address
            page_list.append({page, offset})
            
    for page, offset in page_list:
        entry = tlb.lookup(page)
        frame = None
        if entry is not None:
            frame = entry["frame"]

        # TLB hit
        if frame is not None:
            print(frame) # TEMP
        
        # Page table hit
        elif (entry:=page_table.lookup(page)) is not None:
            frame = entry["frame"]
            # Update TLB on page table hit
            tlb.enqueue(page, frame, True)
        
        # Page table miss, page fault occurs
        else:
            # PRA will determine frame to replace given the full page list (for LRU, OPT)
            # and the current pages in frame (physical_memory)
            frame = pra(page_list, physical_memory)
            victim_page = physical_memory[frame]["page"]
            page_table.unload(victim_page)

            # Update physical_memory frame by looking at backing store
            physical_memory[frame] = {"page": page, "content": backing_store[page]}

            page_table.update(page, frame, True)

            # Update TLB: Add entry to TLB table (and remove stale entries?)
            tlb.enqueue(page, frame, True)

        # Generate output
        content = physical_memory[frame]["content"]
        value_in_bytes = content[offset]
        # Since in bytes, need to convert
        value = struct.unpack('b', bytes([value_in_bytes]))[0]
        print(f"{value}") # TEMP: Need to reformat to the output the assignment is expecting
        
        # TODO: 
        # 1. Lookup TLB, if miss, look at page table (DONE)
        # 2. If page table miss, page fault and load from backing store into frame, update table
        # 3. Update TLB that were missed once in page (DONE)
        # 4. Get value from physical_memory based on offset and index (DONE)
        # 5. Output

        # I think this is the main flow for now, somewhere in 2 I think we'll need our PRA's

        


if __name__ == "__main__":
    main()
