#!/usr/bin/python3
import sys
import os
import struct

PAGE_TABLE_CAPACITY = 256
TLB_CAPACITY = 16
VALID_FRAME_RANGE = range(1, 257)
BACKING_STORE_FILEPATH = "BACKING_STORE.bin"

# Maps a specified victim page to its index in memory
def victim_frame_index(victim, frames):
    for frame_index, frame in enumerate(frames):
        if frame["page"] == victim:
            return frame_index


def find_victim_from_sequence(sequence_slice, frames):
    """
    This is for LRU and OPT algorithms, it takes in a slice of the original sequence which 
    represents either the past pages (LRU) or the upcoming ones (OPT)

    Returns the index of the frame that will be being replaced
    """
    # Holds all pages that are currently in memory            
    candidates = [item["page"] for item in frames] 

    for item in sequence_slice:
        previous_page = item["page"]
        if previous_page in candidates:
            candidates.remove(previous_page)
        
        if (len(candidates) == 1):
            victim_page = candidates[0]
            return victim_frame_index(victim_page, frames)
    
    # If no page in candidates appear again in the sequence, just replace the first
    victim_page = candidates[0]
    return victim_frame_index(victim_page, frames)


# PRA will return frame to evict from physical memory
oldest_frame = None
def pra_fifo(sequence, current_index, frames) -> int:
    global oldest_frame
    total_frames = len(frames)

    # On first page into frame, set oldest to frame 0
    if oldest_frame is None:
        oldest_frame = 0
        return oldest_frame

    # When there exists an oldest frame to exist
    else:
        # Mod by total frames for index cycling 
        frame_to_return = oldest_frame
        oldest_frame = (oldest_frame + 1) % total_frames
        return frame_to_return


def pra_lru(sequence, current_index, frames) -> int:
    return find_victim_from_sequence(sequence[current_index - 1::-1], frames)


def pra_opt(sequence, current_index, frames) -> int:
    return find_victim_from_sequence(sequence[current_index + 1:], frames)


PRA_OPTIONS = {
    "fifo": pra_fifo,
    "lru": pra_lru,
    "opt": pra_opt
}


class TranslationLookasideBuffer:
    def __init__(self):
        self.queue = []

    def enqueue(self, page_number, frame, loaded):
        if len(self.queue) >= TLB_CAPACITY:
            self.queue.pop(0)
        
        self.queue.append({"page": page_number, "frame": frame, "loaded": loaded})

    def lookup(self, page_number):
        for entry in self.queue:
            # Checks if in the queue, and valid bit set
            if entry["page"] == page_number and entry["loaded"]:
                # TLB hit
                return entry
        # TLB miss
        return None
    
    def unload(self, target_page):
        for entry in self.queue:
            if entry["page"] == target_page:
                entry["frame"] = None
                entry["loaded"] = False


class PageTable:
    def __init__(self):
        self.table = []
        # Filling the table with default values
        for _ in range(PAGE_TABLE_CAPACITY):
            self.table.append({"frame": None, "loaded": False})

    def lookup(self, page_number):
        entry = self.table[page_number]
        # Page table hit
        if entry["loaded"]:
            return entry
        # Page table miss
        return None
    
    # This will alter the page table entry for targeted page
    def update(self, target_page, frame, loaded):
        self.table[target_page] = {"frame": frame, "loaded": loaded}
    
    # If a page gets removed from a frame, need to update that entry
    def unload(self, target_page):
        self.table[target_page] = {"frame": None, "loaded": False}


def handle_args() -> tuple[str, int, str]:
    """
    This function ensures the required arguments are provided,
    as well as sets defaults for any optional ones that weren't provided
    """
    args = sys.argv
    argc = len(args)
    frames, pra = None, None

    if argc < 2 or argc > 4:
        print("Usage: memSim <reference-sequence-file.txt> <FRAMES> <PRA>")
        exit()

    filepath = args[1]
    if not os.path.isfile(filepath):
        print(f"File '{filepath}' does not exist")
        exit()

    frames = int(args[2]) if argc >= 3 else 256
    pra_choice = args[3].lower() if argc == 4 else "fifo"

    if frames not in VALID_FRAME_RANGE:
        print("<FRAMES> must be between 1-255")
        exit()

    if pra_choice not in PRA_OPTIONS:
        print("<PRA> must be 'fifo', 'lru' or 'opt'")
        exit()

    pra = PRA_OPTIONS[pra_choice]

    return filepath, frames, pra


def split_virtual_address(addr: int) -> tuple[int, int]:
    # Shift high bits to right to get only the page bits with their appropriate significance
    page = addr >> 8
    # 0xFF has low 8 bits set to 1's and high set to 0's, so & with address to only get the low 8
    offset = addr & 0xFF

    return page, offset


def read_backing():
    """
    Reads in the contents of the provided backing store and stores the data inside a list
    """
    if not os.path.isfile(BACKING_STORE_FILEPATH):
        print(f"'{BACKING_STORE_FILEPATH}' does not exist")
        exit()
    
    backing_contents = []

    with open(BACKING_STORE_FILEPATH, 'rb') as file:
        row = file.read(256)
        backing_contents.append(row)

        while row:
            # extract row table (256 bytes)
            row = file.read(256)
            if not row:
                break
            backing_contents.append(row)

    return backing_contents


def main():
    filepath, frames, pra = handle_args()

    # Initializing all our objects we will use
    tlb = TranslationLookasideBuffer()
    page_table = PageTable()
    backing_store = read_backing()
    physical_memory = []
    page_list = []

    # Counters for output statistics
    page_fault_counter = 0
    tlb_hit_counter = 0
    tlb_miss_counter = 0
    total_addresses = 0

    # Reading in input file and creating the page sequence
    with open(filepath, "r") as file:
        for address in file:
            page, offset = split_virtual_address(int(address.strip()))
            # Load in each address
            page_list.append({"address": address, "page": page, "offset": offset, "visited": False})
            total_addresses += 1
    
    for index, item in enumerate(page_list):
        address, page, offset = item["address"], item["page"], item["offset"]
        item["visited"] = True
        entry = tlb.lookup(page)
        frame = None
        if entry is not None:
            frame = entry["frame"]

        # TLB hit
        if frame is not None:
            tlb_hit_counter += 1
        
        # Page table hit
        elif (entry:=page_table.lookup(page)) is not None:
            frame = entry["frame"]
            # Update TLB on page table hit
            tlb.enqueue(page, frame, True)
            tlb_miss_counter += 1
        
        # Page table miss, page fault occurs
        else:
            # No PRA needed when memory still has room
            if len(physical_memory) < frames:
                physical_memory.append({"page": page, "content": backing_store[page]})
                # Get the index of the frame that was just placed
                frame = len(physical_memory) - 1
            else:
                # Let chosen PRA determine the frame to replace
                frame = pra(page_list, index, physical_memory)
                victim_page = physical_memory[frame]["page"]
                page_table.unload(victim_page)
                tlb.unload(victim_page)
                # Update physical_memory frame by looking at backing store
                physical_memory[frame] = {"page": page, "content": backing_store[page]}

            page_table.update(page, frame, True)
            # Update TLB with the new entry
            tlb.enqueue(page, frame, True)
            tlb_miss_counter += 1
            page_fault_counter += 1

        # Generate output
        content = physical_memory[frame]["content"]
        value_in_bytes = content[offset]
        # Since in bytes, need to convert
        value = struct.unpack('b', bytes([value_in_bytes]))[0]
        # Remove new line from address and convert content to hex
        print(f"{address.rstrip()}, {value}, {frame}, {content.hex().upper()}")

    # Output statistics
    print(f"Number of Translated Addresses = {total_addresses}")
    print(f"Page Faults = {page_fault_counter}")
    print(f"Page Fault Rate = {page_fault_counter/total_addresses:.3f}")
    print(f"TLB Hits = {tlb_hit_counter}")
    print(f"TLB Misses = {tlb_miss_counter}")
    print(f"TLB Hit Rate = {tlb_hit_counter/total_addresses:.3f}")


if __name__ == "__main__":
    main()
